FROM golang:1.23-alpine AS builder
WORKDIR /go/src/volumedriver
COPY . .
RUN go build -o /usr/bin/volumedriver cmd/driver/main.go

FROM alpine:latest
RUN apk add --no-cache ca-certificates \
    && mkdir -p /var/lib/docker/volumes \
    && mkdir -p /var/lib/docker/plugins \
    && chmod 755 /var/lib/docker/volumes \
    && chmod 755 /var/lib/docker/plugins
COPY --from=builder /usr/bin/volumedriver /usr/bin/volumedriver
WORKDIR /
ENTRYPOINT ["/usr/bin/volumedriver"]
