name: 'Build Storage Server'
env:
  PACKAGE_NAME: 'storage-server'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  containerize:
    strategy:
      matrix:
        runner: [blacksmith-2vcpu-ubuntu-2204, blacksmith-2vcpu-ubuntu-2204-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set default tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: echo "TAG_NAME=latest" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/server.Dockerfile
          push: true
          tags: |
            ghcr.io/plexyhost/${{ env.PACKAGE_NAME }}:${{ env.TAG_NAME }}-${{ matrix.runner == 'blacksmith-2vcpu-ubuntu-2204-arm' && 'arm64' || 'amd64' }}
            ghcr.io/plexyhost/${{ env.PACKAGE_NAME }}:latest-${{ matrix.runner == 'blacksmith-2vcpu-ubuntu-2204-arm' && 'arm64' || 'amd64' }}
